language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
#  - oraclejdk8
#  - oraclejdk9
#  - oraclejdk11

sudo: false
install: mvn install -Dgpg.skip -DskipTests -Dmaven.javadoc.skip=true -B -V
script: mvn test